### ISSUE TITLE
stray files in repo (low priority)

### ISSUE THREAD

**Issue by dankelley** [j-harbin/odfToNetCDF#45]
Hi @j-harbin -- hope it's OK to make an issue here.  This is a minor thing but perhaps worth addressing when you have a minute.

I notice that there are some stray files in the repo.  It would make sense to list such files in both `.gitignore` and `.Rbuildignore`, to prevent problems.  There may be other stray files as well.  These are just some that come up quite a lot when using a macOS machine (the `.DS_Store` ones) and using vi (the `.sw*` ones).

Once they are added to `.gitignore` and `.Rbuildignore`, they should also be deleted, just to avoid confusing folks.

```
➜  odfToNetCDF git:(main) git ls-files|grep 'swo\|swp\|.DS_Store'
.DS_Store
sandbox/.DS_Store
sandbox/jlh/.DS_Store
➜  odfToNetCDF git:(main) git checkout matlab
Switched to branch 'matlab'
Your branch is up to date with 'origin/matlab'.
➜  odfToNetCDF git:(matlab) git ls-files|grep 'swo\|swp\|.DS_Store'
.DS_Store
R/.compileOdfToAdp.R.swp
R/.convertNetCDF.R.swp
R/.nameReplacement.R.swp
sandbox/.DS_Store
sandbox/jlh/.DS_Store
```

**Comment by j-harbin** [comment]
Done in commit 23cdca7fc3150d24b48806995ab8069718a15f4d of main. Thanks for the help on this, Dan :)
