### ISSUE TITLE
getCFData() should get CF, BODS, etc. standards

### ISSUE THREAD

**Issue by j-harbin** [j-harbin/odfToNetCDF#57]
Right now `getCFData` gets the standard names, long names, and units for climate and forecast standards. The name of this function should be changed to something like `getStandards()` and have a `type` argument specifying `ctd`, `rcm`, or `adcp` and then a `standard` argument, where the user can give `cf`, `bodc` for (British Oceanographic Data Center), etc.

@richardsc aside from CF and BODC, are there other standards that would be useful? I believe there was a third one mentioned in our meeting the other day.

**Comment by richardsc** [comment]
The other one that was mentioned was "OSNAP", though that's a specific observation program rather than a archival centre. Yuri might know if there's a naming/metadata standard documented somewhere (I suspect there isn't, though ...)

**Comment by j-harbin** [comment]
To do list for tomorrow:

* [ ] update package to have `getStandardData()` instead of `getCFData()`. This will include vignette/ help page images
* [ ] When `standard=BODC` figure out how to still add the CF standard_name into the NetCDF

**Comment by j-harbin** [comment]
Done in commit 02a4892f11230b5cc0b8143e72853987369ca3e3 of the standard branch.
